# Generated by Django 5.2.5 on 2025-08-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Role_Based_auth_app', '0002_alter_user_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('user', 'User'), ('superadmin', 'SuperAdmin')], default='user', max_length=20),
        ),
    ]
